# Generated by Django 5.1.1 on 2024-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_muvi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status_movie',
            field=models.CharField(choices=[('pro', 'pro'), ('silver', 'silver')], default='silver', max_length=10),
        ),
    ]
