# Generated by Django 5.1.1 on 2024-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_muvi', '0002_alter_movie_status_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=15),
        ),
    ]
