# Generated by Django 5.1.1 on 2024-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_muvi', '0003_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='janre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='country_movie', to='online_muvi.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='janre',
            field=models.ManyToManyField(related_name='janre', to='online_muvi.janre'),
        ),
    ]
