# Generated by Django 5.1.1 on 2024-10-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_muvi', '0004_remove_movie_country_remove_movie_janre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_history', to='online_muvi.movie'),
        ),
    ]
