# Generated by Django 5.1.1 on 2024-10-11 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_muvi', '0005_alter_history_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status_movie',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='silver', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
